### ISSUE TITLE
Back-end work required?

### ISSUE THREAD

**Issue by acomito** [howlowck/react-powerbi#1]
I'm not saying this repo should include backedn work, this is just a general question as I'm about to tackle this powerbi-in-react situation. 

Are you doing any back-end work in your react apps, like creating users in powerbi/azure and then authenticating them? The purpose being to show different users different dashboard (or different data in dashboards)? If the data isn't sensitive, it seems you could pass filters in client-side to handle the above, but that's probably not secure enough for 85% of cases.

In my case, I have a standalone react app and people are buying data by the state. I could easily just tag the state to their user records in my DB, and pass them in as a filter, but that seems kind of haphazard. 

Have you come across this situation?

**Comment by Joonaspraks** [comment]
Hi, in your read.me you call the project a "work in progress", but in your todos the only thing referenced is .d.ts. Could you please explain in a few sentences what you would like to see be improved or added to react-powerbi? When would you count the module to be elligible for v1?
