### ISSUE TITLE
Steps before v1

### ISSUE THREAD

**Issue by Joonaspraks** [howlowck/react-powerbi#10]
Hi, in your read.me you call the project a "work in progress", but in your todos the only thing referenced is .d.ts. Could you please explain in a few sentences what you would like to see be improved or added to react-powerbi? When would you count the module to be elligible for v1?

**Comment by howlowck** [comment]
Hi Thanks for the question.  The biggest thing (besides the d.ts file) before I could release to v1 is writting unit and integration tests.  However, I believe several people are already utilizing the package.

**Comment by Joonaspraks** [comment]
Thanks for the reply
