### ISSUE TITLE
Cannot access report with token, using https

### ISSUE THREAD

**Issue by TeaSip** [howlowck/react-powerbi#16]
The report cannot be viewed on deployment website. I wondered the reason why the report can be accessed from local instance but when I deploy in cloud it doesn't work. Note I am using cookies to pass access token in did I do anything wrong?
The token I used is aad access token acquired when the user logs in.

```
<PowerbiEmbedded
    embedType="report" // or "dashboard"
    tokenType="Aad" // or "Aad"
    accessToken={Cookies.get("powerbi")}
    embedUrl="https://app.powerbi.com/reportEmbed?reportId=<reportId>&config=<token>"
    id="reportId"
    filterPaneEnabled={false}
    navContentPaneEnabled={true}
    onEmbedded={this.onEmbedded}
    pageView="fitToWidth"  
    width="100%"
    height="100%"
    className="iframeContainer"
    display="initial"
    sandbox="allow-forms allow-popups allow-pointer-lock allow-same-origin allow-scripts"
    position="relative"
    styles={{ height: "93vh" }}
/>
```

<img width="1429" alt="Screen Shot 2020-01-08 at 11 02 04 AM" src="https://user-images.githubusercontent.com/11391807/71994205-55dd9900-3206-11ea-8dc8-f953515606ea.png">

**Comment by howlowck** [comment]
Are you able to get the `powerbi` value from `Cookie`?

**Comment by TeaSip** [comment]
@howlowck  Thanks for replying. I actually got cookie working, since previously what in the screenshot happens when cookie expires (not the Aad access token).
So after I set the expiry time of the cookie to sync with the Aad access token life span, it worked.

But here what I'd like to know more is, what is the best practice for handle that access token in the react front-end? I get the cookie value and store it in react component's state. (Not sure if that secure the token from been stolen)

Also what would you suggest to do after, the access token expired (right now it expire in one hour)?

**Comment by howlowck** [comment]
For React and AAD, the easiest way I know of is to use the [react-aad-msal](https://github.com/syncweek-react-aad/react-aad/blob/master/README.md) library. It will be able to seamlessly supply you with the access token. It uses the msal library to either refresh the token or redirect the user to login in. It also nicely integrates with redux, which is how I use this library to get the AAD access token.

Hope that helps.

**Comment by TeaSip** [comment]
Thank you so much!
I have been using passport-azure-ad library OIDC for some single sign-on
features. Definitely worthy to explore the option you suggested too. Have a
great day. I think I can close this issue.
