### ISSUE TITLE
Restart embeded report on "mobile" change

### ISSUE THREAD

**Issue by veewee** [howlowck/react-powerbi#24]
Hello,

First and for all : thanks for this package!

I wrapped a report with react-media to make it switch report modes.
The layout type works when I set the screen resolution correct before loading the component.
However, when I change the window width once the report is loaded, the report doesn't take the mobile property into consideration. This property is set correctly by the react-media component. Next the `PowerbiEmbedded` components reloads with the initial layout type.

Expected behaviour : the report should load with correct layout type when I switch the windows size.

The code looks like this:

```js
import * as React from 'react';
import Media from 'react-media';
import PowerbiEmbedded from 'react-powerbi';

const Report = (props: IProps) => (
  <Media
    queries={{
      phone: "(max-width: 767px)",
      tablet: "(min-width: 768px) and (max-width: 991px)",
      desktop: "(min-width: 992px)"
    }}
  >
    {matches => (
      <>
        <PowerbiEmbedded
          id={props.reportId}
          embedUrl={props.embedUrl}
          accessToken={props.embedToken}
          filterPaneEnabled={ false }
          navContentPaneEnabled={ false }
          mobile={matches.phone}
        />
      </>
    )}
  </Media>
);

export default Report;
```

**Comment by howlowck** [comment]
@veewee I will try to take a look this weekend. If not next week. Thanks for raising an issue about it.

**Comment by howlowck** [comment]
hi @veewee, does the component render correctly (in mobile mode) if you set `mobile={true}` before the component renders for the first time?

**Comment by veewee** [comment]
If I render the component in a mobile view first, it loads the mobile view of the powerbi report. If I change the width to full desktop width without reloading the page, it still loads the mobile view of the report instead of the desktop view.

**Comment by howlowck** [comment]
@veewee make sure you upgrade to 0.9.0 and try again. I'll reopen if it doesn't work.
For future reference this is the reason why it wasn't working: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-For-Mobile#change-layout-example
we needed to `reset` the container.

**Comment by veewee** [comment]
Thanks for the super quick fix @howlowck ! It works like a charm!
