### ISSUE TITLE
Typescript is not able to detect powerbi specific properties

### ISSUE THREAD

**Issue by veewee** [howlowck/react-powerbi#28]
Hello @howlowck,

In the 0.9.0 release, typescript is not able to determine the powerBI specific properties:

```
TS2322: Type '{ id: string; embedUrl: string; accessToken: string; filterPaneEnabled: false; navContentPaneEnabled: false; height: string; mobile: boolean; }' is not assignable to type 'IntrinsicAttributes & PowerBIEmbeddedProps & { children?: ReactNode; }'.
  Property 'embedUrl' does not exist on type 'IntrinsicAttributes & PowerBIEmbeddedProps & { children?: ReactNode; }'.
```

It complains about all power-bi client specific models:

* embedUrl
* accessToken
* height

My report is pretty simple:
```
        <PowerbiEmbedded
          id={props.report.id}
          embedUrl={props.report.embedUrl}
          accessToken={props.embed.token}
          filterPaneEnabled={ false }
          navContentPaneEnabled={ false }
          height="800px"
          mobile={matches.phone}
        />
```

I think it is related to this commit:

https://github.com/howlowck/react-powerbi/commit/1bde300cf6f0963349d02974abbde8de9604680a#diff-0e3ac3694919aca1db302bc3ebe669f2

**Comment by howlowck** [comment]
yikes.. that's not good. I'll take a look today

**Comment by kgjersda** [comment]
I also have this exact problem.

**Comment by howlowck** [comment]
Hey upgrade to 0.9.1 and it should fix the typing issue.

**Comment by kgjersda** [comment]
I deleted node_modules and upgraded packages, it solved the problem. Will
try the new version also.

**Comment by veewee** [comment]
Thanks!
