### ISSUE TITLE
AccessToken?

### ISSUE THREAD

**Issue by loconluis** [howlowck/react-powerbi#3]
What is the meaning of AccessToken?? Im generate a EmbedToken for a single Report, But is not accepted.

**Comment by jacobdanovitch** [comment]
Having this issue as well. The component renders with a "This content isn't available" message.

**Comment by wjfuoco** [comment]
I'm having this same issue rendering "This content isn't available".  Any thoughts yet?

**Comment by wjfuoco** [comment]
I figured out how to resolve the "This content isn't available" message.  You'll need to ad into your JSX tokenType={1} which clarifies this is an embed, or if using AAD tokenType={0}.

`<div className='App'>
        <PowerbiEmbedded
          id={`${YOUR_REPORT_ID}`}
          tokenType={1}
          embedUrl={`${YOUR_EMBED_URL}`}
          accessToken={`${YOUR_EMBED_TOKEN}`}
          filterPaneEnabled={false}
          navContentPaneEnabled={false}
          width='600px'
          height='900px'
        />
      </div>`

**Comment by loconluis** [comment]
@wjfuoco TokenType prop works for me! Thank you very much!!!

I think this component needs a lot of work, but is a great base, to show something quickly.

Thanks!!!

**Comment by jacobdanovitch** [comment]
Sorry to come back to this after closing, but I'm still getting this error seemingly randomly.

Started off with tokenType={1}. Toggled back and forth {0} a couple times.
Resized a couple times, nothing worked.
Moved around the order of the props (just for ease with copy/pasting from the demo), and all of a sudden, it worked.

**Comment by wjfuoco** [comment]
Glad it started working for you though.  I ultimately abandoned and implemented the Microsoft Javascript SDK into my React app.  More clunky, but now I have full control over the configuration of the embed, and can also embed Dashboards and single Visualizations as-needed.
